### ISSUE TITLE
Problem with tagging on CPU

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [PonteIneptique/boudams#26]
When tagging on CPU (with model trained on CUDA), I get the following error:

```
 boudams tag --device cpu models/fro_denorm.boudams_model train_cleaned/*
Loading the model.
Traceback (most recent call last):
  File "/home/jbcamps/boudams-env/bin/boudams", line 8, in <module>
    sys.exit(cli())
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/boudams/cli.py", line 411, in tag
    model = BoudamsTagger.load(model)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/boudams/tagger.py", line 490, in load
    obj.load_state_dict(torch.load(dictpath), strict=False)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/jbcamps/boudams-env/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine
```

**Comment by Jean-Baptiste-Camps** [comment]
In addition,
- [Sample model](https://github.com/Jean-Baptiste-Camps/trouveres_stylometry/tree/main/models)
- [Some data](https://github.com/Jean-Baptiste-Camps/trouveres_stylometry/tree/main/train_cleaned)

**Comment by Jean-Baptiste-Camps** [comment]
NB: tagging works fine on CUDA.
